language: node_js

node_js:
  - "stable"

sudo: true

before_script:
  - npm install -g typescript typings
  - typings install && tsc

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sudo apt-get update
  - sh -e /etc/init.d/xvfb start
